// Code generated by mockery v2.42.0. DO NOT EDIT.

package eventbusconnect_mocks

import (
	context "context"

	connect "connectrpc.com/connect"

	eventbus "github.com/infinimesh/proto/eventbus"

	mock "github.com/stretchr/testify/mock"

	node "github.com/infinimesh/proto/node"
)

// MockEventsServiceClient is an autogenerated mock type for the EventsServiceClient type
type MockEventsServiceClient struct {
	mock.Mock
}

type MockEventsServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventsServiceClient) EXPECT() *MockEventsServiceClient_Expecter {
	return &MockEventsServiceClient_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function with given fields: _a0, _a1
func (_m *MockEventsServiceClient) Subscribe(_a0 context.Context, _a1 *connect.Request[node.EmptyMessage]) (*connect.ServerStreamForClient[eventbus.Event], error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 *connect.ServerStreamForClient[eventbus.Event]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *connect.Request[node.EmptyMessage]) (*connect.ServerStreamForClient[eventbus.Event], error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *connect.Request[node.EmptyMessage]) *connect.ServerStreamForClient[eventbus.Event]); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connect.ServerStreamForClient[eventbus.Event])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *connect.Request[node.EmptyMessage]) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventsServiceClient_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockEventsServiceClient_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *connect.Request[node.EmptyMessage]
func (_e *MockEventsServiceClient_Expecter) Subscribe(_a0 interface{}, _a1 interface{}) *MockEventsServiceClient_Subscribe_Call {
	return &MockEventsServiceClient_Subscribe_Call{Call: _e.mock.On("Subscribe", _a0, _a1)}
}

func (_c *MockEventsServiceClient_Subscribe_Call) Run(run func(_a0 context.Context, _a1 *connect.Request[node.EmptyMessage])) *MockEventsServiceClient_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*connect.Request[node.EmptyMessage]))
	})
	return _c
}

func (_c *MockEventsServiceClient_Subscribe_Call) Return(_a0 *connect.ServerStreamForClient[eventbus.Event], _a1 error) *MockEventsServiceClient_Subscribe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventsServiceClient_Subscribe_Call) RunAndReturn(run func(context.Context, *connect.Request[node.EmptyMessage]) (*connect.ServerStreamForClient[eventbus.Event], error)) *MockEventsServiceClient_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventsServiceClient creates a new instance of MockEventsServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventsServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventsServiceClient {
	mock := &MockEventsServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
