//
//Copyright © 2021-2023 Infinite Devices GmbH
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: shadow/shadow.proto

package shadowconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	shadow "github.com/infinimesh/proto/shadow"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// ShadowServiceName is the fully-qualified name of the ShadowService service.
	ShadowServiceName = "infinimesh.shadow.ShadowService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ShadowServiceGetProcedure is the fully-qualified name of the ShadowService's Get RPC.
	ShadowServiceGetProcedure = "/infinimesh.shadow.ShadowService/Get"
	// ShadowServicePatchProcedure is the fully-qualified name of the ShadowService's Patch RPC.
	ShadowServicePatchProcedure = "/infinimesh.shadow.ShadowService/Patch"
	// ShadowServiceRemoveProcedure is the fully-qualified name of the ShadowService's Remove RPC.
	ShadowServiceRemoveProcedure = "/infinimesh.shadow.ShadowService/Remove"
	// ShadowServiceStreamShadowProcedure is the fully-qualified name of the ShadowService's
	// StreamShadow RPC.
	ShadowServiceStreamShadowProcedure = "/infinimesh.shadow.ShadowService/StreamShadow"
)

// ShadowServiceClient is a client for the infinimesh.shadow.ShadowService service.
type ShadowServiceClient interface {
	Get(context.Context, *connect_go.Request[shadow.GetRequest]) (*connect_go.Response[shadow.GetResponse], error)
	Patch(context.Context, *connect_go.Request[shadow.Shadow]) (*connect_go.Response[shadow.Shadow], error)
	Remove(context.Context, *connect_go.Request[shadow.RemoveRequest]) (*connect_go.Response[shadow.Shadow], error)
	StreamShadow(context.Context, *connect_go.Request[shadow.StreamShadowRequest]) (*connect_go.ServerStreamForClient[shadow.Shadow], error)
}

// NewShadowServiceClient constructs a client for the infinimesh.shadow.ShadowService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewShadowServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) ShadowServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &shadowServiceClient{
		get: connect_go.NewClient[shadow.GetRequest, shadow.GetResponse](
			httpClient,
			baseURL+ShadowServiceGetProcedure,
			opts...,
		),
		patch: connect_go.NewClient[shadow.Shadow, shadow.Shadow](
			httpClient,
			baseURL+ShadowServicePatchProcedure,
			opts...,
		),
		remove: connect_go.NewClient[shadow.RemoveRequest, shadow.Shadow](
			httpClient,
			baseURL+ShadowServiceRemoveProcedure,
			opts...,
		),
		streamShadow: connect_go.NewClient[shadow.StreamShadowRequest, shadow.Shadow](
			httpClient,
			baseURL+ShadowServiceStreamShadowProcedure,
			opts...,
		),
	}
}

// shadowServiceClient implements ShadowServiceClient.
type shadowServiceClient struct {
	get          *connect_go.Client[shadow.GetRequest, shadow.GetResponse]
	patch        *connect_go.Client[shadow.Shadow, shadow.Shadow]
	remove       *connect_go.Client[shadow.RemoveRequest, shadow.Shadow]
	streamShadow *connect_go.Client[shadow.StreamShadowRequest, shadow.Shadow]
}

// Get calls infinimesh.shadow.ShadowService.Get.
func (c *shadowServiceClient) Get(ctx context.Context, req *connect_go.Request[shadow.GetRequest]) (*connect_go.Response[shadow.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// Patch calls infinimesh.shadow.ShadowService.Patch.
func (c *shadowServiceClient) Patch(ctx context.Context, req *connect_go.Request[shadow.Shadow]) (*connect_go.Response[shadow.Shadow], error) {
	return c.patch.CallUnary(ctx, req)
}

// Remove calls infinimesh.shadow.ShadowService.Remove.
func (c *shadowServiceClient) Remove(ctx context.Context, req *connect_go.Request[shadow.RemoveRequest]) (*connect_go.Response[shadow.Shadow], error) {
	return c.remove.CallUnary(ctx, req)
}

// StreamShadow calls infinimesh.shadow.ShadowService.StreamShadow.
func (c *shadowServiceClient) StreamShadow(ctx context.Context, req *connect_go.Request[shadow.StreamShadowRequest]) (*connect_go.ServerStreamForClient[shadow.Shadow], error) {
	return c.streamShadow.CallServerStream(ctx, req)
}

// ShadowServiceHandler is an implementation of the infinimesh.shadow.ShadowService service.
type ShadowServiceHandler interface {
	Get(context.Context, *connect_go.Request[shadow.GetRequest]) (*connect_go.Response[shadow.GetResponse], error)
	Patch(context.Context, *connect_go.Request[shadow.Shadow]) (*connect_go.Response[shadow.Shadow], error)
	Remove(context.Context, *connect_go.Request[shadow.RemoveRequest]) (*connect_go.Response[shadow.Shadow], error)
	StreamShadow(context.Context, *connect_go.Request[shadow.StreamShadowRequest], *connect_go.ServerStream[shadow.Shadow]) error
}

// NewShadowServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewShadowServiceHandler(svc ShadowServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle(ShadowServiceGetProcedure, connect_go.NewUnaryHandler(
		ShadowServiceGetProcedure,
		svc.Get,
		opts...,
	))
	mux.Handle(ShadowServicePatchProcedure, connect_go.NewUnaryHandler(
		ShadowServicePatchProcedure,
		svc.Patch,
		opts...,
	))
	mux.Handle(ShadowServiceRemoveProcedure, connect_go.NewUnaryHandler(
		ShadowServiceRemoveProcedure,
		svc.Remove,
		opts...,
	))
	mux.Handle(ShadowServiceStreamShadowProcedure, connect_go.NewServerStreamHandler(
		ShadowServiceStreamShadowProcedure,
		svc.StreamShadow,
		opts...,
	))
	return "/infinimesh.shadow.ShadowService/", mux
}

// UnimplementedShadowServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedShadowServiceHandler struct{}

func (UnimplementedShadowServiceHandler) Get(context.Context, *connect_go.Request[shadow.GetRequest]) (*connect_go.Response[shadow.GetResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("infinimesh.shadow.ShadowService.Get is not implemented"))
}

func (UnimplementedShadowServiceHandler) Patch(context.Context, *connect_go.Request[shadow.Shadow]) (*connect_go.Response[shadow.Shadow], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("infinimesh.shadow.ShadowService.Patch is not implemented"))
}

func (UnimplementedShadowServiceHandler) Remove(context.Context, *connect_go.Request[shadow.RemoveRequest]) (*connect_go.Response[shadow.Shadow], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("infinimesh.shadow.ShadowService.Remove is not implemented"))
}

func (UnimplementedShadowServiceHandler) StreamShadow(context.Context, *connect_go.Request[shadow.StreamShadowRequest], *connect_go.ServerStream[shadow.Shadow]) error {
	return connect_go.NewError(connect_go.CodeUnimplemented, errors.New("infinimesh.shadow.ShadowService.StreamShadow is not implemented"))
}
