//
//Copyright © 2021-2023 Infinite Devices GmbH
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: node/node.proto

package node

import (
	context "context"
	access "github.com/infinimesh/proto/node/access"
	accounts "github.com/infinimesh/proto/node/accounts"
	devices "github.com/infinimesh/proto/node/devices"
	namespaces "github.com/infinimesh/proto/node/namespaces"
	sessions "github.com/infinimesh/proto/node/sessions"
	shadow "github.com/infinimesh/proto/shadow"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AccountsService_Token_FullMethodName          = "/infinimesh.node.AccountsService/Token"
	AccountsService_Get_FullMethodName            = "/infinimesh.node.AccountsService/Get"
	AccountsService_List_FullMethodName           = "/infinimesh.node.AccountsService/List"
	AccountsService_Create_FullMethodName         = "/infinimesh.node.AccountsService/Create"
	AccountsService_Update_FullMethodName         = "/infinimesh.node.AccountsService/Update"
	AccountsService_Toggle_FullMethodName         = "/infinimesh.node.AccountsService/Toggle"
	AccountsService_Delete_FullMethodName         = "/infinimesh.node.AccountsService/Delete"
	AccountsService_Accessibles_FullMethodName    = "/infinimesh.node.AccountsService/Accessibles"
	AccountsService_Deletables_FullMethodName     = "/infinimesh.node.AccountsService/Deletables"
	AccountsService_Move_FullMethodName           = "/infinimesh.node.AccountsService/Move"
	AccountsService_GetCredentials_FullMethodName = "/infinimesh.node.AccountsService/GetCredentials"
	AccountsService_SetCredentials_FullMethodName = "/infinimesh.node.AccountsService/SetCredentials"
	AccountsService_DelCredentials_FullMethodName = "/infinimesh.node.AccountsService/DelCredentials"
)

// AccountsServiceClient is the client API for AccountsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountsServiceClient interface {
	Token(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	Get(ctx context.Context, in *accounts.Account, opts ...grpc.CallOption) (*accounts.Account, error)
	List(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*accounts.Accounts, error)
	Create(ctx context.Context, in *accounts.CreateRequest, opts ...grpc.CallOption) (*accounts.CreateResponse, error)
	Update(ctx context.Context, in *accounts.Account, opts ...grpc.CallOption) (*accounts.Account, error)
	Toggle(ctx context.Context, in *accounts.Account, opts ...grpc.CallOption) (*accounts.Account, error)
	Delete(ctx context.Context, in *accounts.Account, opts ...grpc.CallOption) (*DeleteResponse, error)
	Accessibles(ctx context.Context, in *namespaces.Namespace, opts ...grpc.CallOption) (*access.Nodes, error)
	Deletables(ctx context.Context, in *accounts.Account, opts ...grpc.CallOption) (*access.Nodes, error)
	Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	GetCredentials(ctx context.Context, in *GetCredentialsRequest, opts ...grpc.CallOption) (*GetCredentialsResponse, error)
	SetCredentials(ctx context.Context, in *SetCredentialsRequest, opts ...grpc.CallOption) (*SetCredentialsResponse, error)
	DelCredentials(ctx context.Context, in *DeleteCredentialsRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type accountsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountsServiceClient(cc grpc.ClientConnInterface) AccountsServiceClient {
	return &accountsServiceClient{cc}
}

func (c *accountsServiceClient) Token(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, AccountsService_Token_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) Get(ctx context.Context, in *accounts.Account, opts ...grpc.CallOption) (*accounts.Account, error) {
	out := new(accounts.Account)
	err := c.cc.Invoke(ctx, AccountsService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) List(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*accounts.Accounts, error) {
	out := new(accounts.Accounts)
	err := c.cc.Invoke(ctx, AccountsService_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) Create(ctx context.Context, in *accounts.CreateRequest, opts ...grpc.CallOption) (*accounts.CreateResponse, error) {
	out := new(accounts.CreateResponse)
	err := c.cc.Invoke(ctx, AccountsService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) Update(ctx context.Context, in *accounts.Account, opts ...grpc.CallOption) (*accounts.Account, error) {
	out := new(accounts.Account)
	err := c.cc.Invoke(ctx, AccountsService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) Toggle(ctx context.Context, in *accounts.Account, opts ...grpc.CallOption) (*accounts.Account, error) {
	out := new(accounts.Account)
	err := c.cc.Invoke(ctx, AccountsService_Toggle_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) Delete(ctx context.Context, in *accounts.Account, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, AccountsService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) Accessibles(ctx context.Context, in *namespaces.Namespace, opts ...grpc.CallOption) (*access.Nodes, error) {
	out := new(access.Nodes)
	err := c.cc.Invoke(ctx, AccountsService_Accessibles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) Deletables(ctx context.Context, in *accounts.Account, opts ...grpc.CallOption) (*access.Nodes, error) {
	out := new(access.Nodes)
	err := c.cc.Invoke(ctx, AccountsService_Deletables_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, AccountsService_Move_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) GetCredentials(ctx context.Context, in *GetCredentialsRequest, opts ...grpc.CallOption) (*GetCredentialsResponse, error) {
	out := new(GetCredentialsResponse)
	err := c.cc.Invoke(ctx, AccountsService_GetCredentials_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) SetCredentials(ctx context.Context, in *SetCredentialsRequest, opts ...grpc.CallOption) (*SetCredentialsResponse, error) {
	out := new(SetCredentialsResponse)
	err := c.cc.Invoke(ctx, AccountsService_SetCredentials_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) DelCredentials(ctx context.Context, in *DeleteCredentialsRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, AccountsService_DelCredentials_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsServiceServer is the server API for AccountsService service.
// All implementations must embed UnimplementedAccountsServiceServer
// for forward compatibility
type AccountsServiceServer interface {
	Token(context.Context, *TokenRequest) (*TokenResponse, error)
	Get(context.Context, *accounts.Account) (*accounts.Account, error)
	List(context.Context, *EmptyMessage) (*accounts.Accounts, error)
	Create(context.Context, *accounts.CreateRequest) (*accounts.CreateResponse, error)
	Update(context.Context, *accounts.Account) (*accounts.Account, error)
	Toggle(context.Context, *accounts.Account) (*accounts.Account, error)
	Delete(context.Context, *accounts.Account) (*DeleteResponse, error)
	Accessibles(context.Context, *namespaces.Namespace) (*access.Nodes, error)
	Deletables(context.Context, *accounts.Account) (*access.Nodes, error)
	Move(context.Context, *MoveRequest) (*EmptyMessage, error)
	GetCredentials(context.Context, *GetCredentialsRequest) (*GetCredentialsResponse, error)
	SetCredentials(context.Context, *SetCredentialsRequest) (*SetCredentialsResponse, error)
	DelCredentials(context.Context, *DeleteCredentialsRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedAccountsServiceServer()
}

// UnimplementedAccountsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAccountsServiceServer struct {
}

func (UnimplementedAccountsServiceServer) Token(context.Context, *TokenRequest) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Token not implemented")
}
func (UnimplementedAccountsServiceServer) Get(context.Context, *accounts.Account) (*accounts.Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAccountsServiceServer) List(context.Context, *EmptyMessage) (*accounts.Accounts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAccountsServiceServer) Create(context.Context, *accounts.CreateRequest) (*accounts.CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAccountsServiceServer) Update(context.Context, *accounts.Account) (*accounts.Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAccountsServiceServer) Toggle(context.Context, *accounts.Account) (*accounts.Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Toggle not implemented")
}
func (UnimplementedAccountsServiceServer) Delete(context.Context, *accounts.Account) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAccountsServiceServer) Accessibles(context.Context, *namespaces.Namespace) (*access.Nodes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Accessibles not implemented")
}
func (UnimplementedAccountsServiceServer) Deletables(context.Context, *accounts.Account) (*access.Nodes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deletables not implemented")
}
func (UnimplementedAccountsServiceServer) Move(context.Context, *MoveRequest) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Move not implemented")
}
func (UnimplementedAccountsServiceServer) GetCredentials(context.Context, *GetCredentialsRequest) (*GetCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCredentials not implemented")
}
func (UnimplementedAccountsServiceServer) SetCredentials(context.Context, *SetCredentialsRequest) (*SetCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCredentials not implemented")
}
func (UnimplementedAccountsServiceServer) DelCredentials(context.Context, *DeleteCredentialsRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelCredentials not implemented")
}
func (UnimplementedAccountsServiceServer) mustEmbedUnimplementedAccountsServiceServer() {}

// UnsafeAccountsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountsServiceServer will
// result in compilation errors.
type UnsafeAccountsServiceServer interface {
	mustEmbedUnimplementedAccountsServiceServer()
}

func RegisterAccountsServiceServer(s grpc.ServiceRegistrar, srv AccountsServiceServer) {
	s.RegisterService(&AccountsService_ServiceDesc, srv)
}

func _AccountsService_Token_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).Token(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_Token_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).Token(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).Get(ctx, req.(*accounts.Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).List(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).Create(ctx, req.(*accounts.CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).Update(ctx, req.(*accounts.Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_Toggle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).Toggle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_Toggle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).Toggle(ctx, req.(*accounts.Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).Delete(ctx, req.(*accounts.Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_Accessibles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(namespaces.Namespace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).Accessibles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_Accessibles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).Accessibles(ctx, req.(*namespaces.Namespace))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_Deletables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).Deletables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_Deletables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).Deletables(ctx, req.(*accounts.Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_Move_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).Move(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_GetCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).GetCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_GetCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).GetCredentials(ctx, req.(*GetCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_SetCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).SetCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_SetCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).SetCredentials(ctx, req.(*SetCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_DelCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).DelCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_DelCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).DelCredentials(ctx, req.(*DeleteCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountsService_ServiceDesc is the grpc.ServiceDesc for AccountsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.node.AccountsService",
	HandlerType: (*AccountsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Token",
			Handler:    _AccountsService_Token_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AccountsService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AccountsService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AccountsService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AccountsService_Update_Handler,
		},
		{
			MethodName: "Toggle",
			Handler:    _AccountsService_Toggle_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AccountsService_Delete_Handler,
		},
		{
			MethodName: "Accessibles",
			Handler:    _AccountsService_Accessibles_Handler,
		},
		{
			MethodName: "Deletables",
			Handler:    _AccountsService_Deletables_Handler,
		},
		{
			MethodName: "Move",
			Handler:    _AccountsService_Move_Handler,
		},
		{
			MethodName: "GetCredentials",
			Handler:    _AccountsService_GetCredentials_Handler,
		},
		{
			MethodName: "SetCredentials",
			Handler:    _AccountsService_SetCredentials_Handler,
		},
		{
			MethodName: "DelCredentials",
			Handler:    _AccountsService_DelCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node/node.proto",
}

const (
	SessionsService_Get_FullMethodName         = "/infinimesh.node.SessionsService/Get"
	SessionsService_Revoke_FullMethodName      = "/infinimesh.node.SessionsService/Revoke"
	SessionsService_GetActivity_FullMethodName = "/infinimesh.node.SessionsService/GetActivity"
)

// SessionsServiceClient is the client API for SessionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionsServiceClient interface {
	Get(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*sessions.Sessions, error)
	Revoke(ctx context.Context, in *sessions.Session, opts ...grpc.CallOption) (*DeleteResponse, error)
	GetActivity(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*sessions.Activity, error)
}

type sessionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionsServiceClient(cc grpc.ClientConnInterface) SessionsServiceClient {
	return &sessionsServiceClient{cc}
}

func (c *sessionsServiceClient) Get(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*sessions.Sessions, error) {
	out := new(sessions.Sessions)
	err := c.cc.Invoke(ctx, SessionsService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) Revoke(ctx context.Context, in *sessions.Session, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, SessionsService_Revoke_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) GetActivity(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*sessions.Activity, error) {
	out := new(sessions.Activity)
	err := c.cc.Invoke(ctx, SessionsService_GetActivity_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionsServiceServer is the server API for SessionsService service.
// All implementations must embed UnimplementedSessionsServiceServer
// for forward compatibility
type SessionsServiceServer interface {
	Get(context.Context, *EmptyMessage) (*sessions.Sessions, error)
	Revoke(context.Context, *sessions.Session) (*DeleteResponse, error)
	GetActivity(context.Context, *EmptyMessage) (*sessions.Activity, error)
	mustEmbedUnimplementedSessionsServiceServer()
}

// UnimplementedSessionsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSessionsServiceServer struct {
}

func (UnimplementedSessionsServiceServer) Get(context.Context, *EmptyMessage) (*sessions.Sessions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSessionsServiceServer) Revoke(context.Context, *sessions.Session) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedSessionsServiceServer) GetActivity(context.Context, *EmptyMessage) (*sessions.Activity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivity not implemented")
}
func (UnimplementedSessionsServiceServer) mustEmbedUnimplementedSessionsServiceServer() {}

// UnsafeSessionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionsServiceServer will
// result in compilation errors.
type UnsafeSessionsServiceServer interface {
	mustEmbedUnimplementedSessionsServiceServer()
}

func RegisterSessionsServiceServer(s grpc.ServiceRegistrar, srv SessionsServiceServer) {
	s.RegisterService(&SessionsService_ServiceDesc, srv)
}

func _SessionsService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).Get(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(sessions.Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_Revoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).Revoke(ctx, req.(*sessions.Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_GetActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).GetActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_GetActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).GetActivity(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionsService_ServiceDesc is the grpc.ServiceDesc for SessionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.node.SessionsService",
	HandlerType: (*SessionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _SessionsService_Get_Handler,
		},
		{
			MethodName: "Revoke",
			Handler:    _SessionsService_Revoke_Handler,
		},
		{
			MethodName: "GetActivity",
			Handler:    _SessionsService_GetActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node/node.proto",
}

const (
	NamespacesService_Get_FullMethodName         = "/infinimesh.node.NamespacesService/Get"
	NamespacesService_List_FullMethodName        = "/infinimesh.node.NamespacesService/List"
	NamespacesService_Create_FullMethodName      = "/infinimesh.node.NamespacesService/Create"
	NamespacesService_Update_FullMethodName      = "/infinimesh.node.NamespacesService/Update"
	NamespacesService_Delete_FullMethodName      = "/infinimesh.node.NamespacesService/Delete"
	NamespacesService_Accessibles_FullMethodName = "/infinimesh.node.NamespacesService/Accessibles"
	NamespacesService_Deletables_FullMethodName  = "/infinimesh.node.NamespacesService/Deletables"
	NamespacesService_Joins_FullMethodName       = "/infinimesh.node.NamespacesService/Joins"
	NamespacesService_Join_FullMethodName        = "/infinimesh.node.NamespacesService/Join"
)

// NamespacesServiceClient is the client API for NamespacesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NamespacesServiceClient interface {
	Get(ctx context.Context, in *namespaces.Namespace, opts ...grpc.CallOption) (*namespaces.Namespace, error)
	List(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*namespaces.Namespaces, error)
	Create(ctx context.Context, in *namespaces.Namespace, opts ...grpc.CallOption) (*namespaces.Namespace, error)
	Update(ctx context.Context, in *namespaces.Namespace, opts ...grpc.CallOption) (*namespaces.Namespace, error)
	Delete(ctx context.Context, in *namespaces.Namespace, opts ...grpc.CallOption) (*DeleteResponse, error)
	Accessibles(ctx context.Context, in *namespaces.Namespace, opts ...grpc.CallOption) (*access.Nodes, error)
	Deletables(ctx context.Context, in *namespaces.Namespace, opts ...grpc.CallOption) (*access.Nodes, error)
	// Accounts having access to this namespace
	Joins(ctx context.Context, in *namespaces.Namespace, opts ...grpc.CallOption) (*accounts.Accounts, error)
	// Sets Access to this namespace for the given account(deletes if level is set
	// to NONE(0))
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*accounts.Accounts, error)
}

type namespacesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNamespacesServiceClient(cc grpc.ClientConnInterface) NamespacesServiceClient {
	return &namespacesServiceClient{cc}
}

func (c *namespacesServiceClient) Get(ctx context.Context, in *namespaces.Namespace, opts ...grpc.CallOption) (*namespaces.Namespace, error) {
	out := new(namespaces.Namespace)
	err := c.cc.Invoke(ctx, NamespacesService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespacesServiceClient) List(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*namespaces.Namespaces, error) {
	out := new(namespaces.Namespaces)
	err := c.cc.Invoke(ctx, NamespacesService_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespacesServiceClient) Create(ctx context.Context, in *namespaces.Namespace, opts ...grpc.CallOption) (*namespaces.Namespace, error) {
	out := new(namespaces.Namespace)
	err := c.cc.Invoke(ctx, NamespacesService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespacesServiceClient) Update(ctx context.Context, in *namespaces.Namespace, opts ...grpc.CallOption) (*namespaces.Namespace, error) {
	out := new(namespaces.Namespace)
	err := c.cc.Invoke(ctx, NamespacesService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespacesServiceClient) Delete(ctx context.Context, in *namespaces.Namespace, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, NamespacesService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespacesServiceClient) Accessibles(ctx context.Context, in *namespaces.Namespace, opts ...grpc.CallOption) (*access.Nodes, error) {
	out := new(access.Nodes)
	err := c.cc.Invoke(ctx, NamespacesService_Accessibles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespacesServiceClient) Deletables(ctx context.Context, in *namespaces.Namespace, opts ...grpc.CallOption) (*access.Nodes, error) {
	out := new(access.Nodes)
	err := c.cc.Invoke(ctx, NamespacesService_Deletables_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespacesServiceClient) Joins(ctx context.Context, in *namespaces.Namespace, opts ...grpc.CallOption) (*accounts.Accounts, error) {
	out := new(accounts.Accounts)
	err := c.cc.Invoke(ctx, NamespacesService_Joins_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespacesServiceClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*accounts.Accounts, error) {
	out := new(accounts.Accounts)
	err := c.cc.Invoke(ctx, NamespacesService_Join_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NamespacesServiceServer is the server API for NamespacesService service.
// All implementations must embed UnimplementedNamespacesServiceServer
// for forward compatibility
type NamespacesServiceServer interface {
	Get(context.Context, *namespaces.Namespace) (*namespaces.Namespace, error)
	List(context.Context, *EmptyMessage) (*namespaces.Namespaces, error)
	Create(context.Context, *namespaces.Namespace) (*namespaces.Namespace, error)
	Update(context.Context, *namespaces.Namespace) (*namespaces.Namespace, error)
	Delete(context.Context, *namespaces.Namespace) (*DeleteResponse, error)
	Accessibles(context.Context, *namespaces.Namespace) (*access.Nodes, error)
	Deletables(context.Context, *namespaces.Namespace) (*access.Nodes, error)
	// Accounts having access to this namespace
	Joins(context.Context, *namespaces.Namespace) (*accounts.Accounts, error)
	// Sets Access to this namespace for the given account(deletes if level is set
	// to NONE(0))
	Join(context.Context, *JoinRequest) (*accounts.Accounts, error)
	mustEmbedUnimplementedNamespacesServiceServer()
}

// UnimplementedNamespacesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNamespacesServiceServer struct {
}

func (UnimplementedNamespacesServiceServer) Get(context.Context, *namespaces.Namespace) (*namespaces.Namespace, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedNamespacesServiceServer) List(context.Context, *EmptyMessage) (*namespaces.Namespaces, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedNamespacesServiceServer) Create(context.Context, *namespaces.Namespace) (*namespaces.Namespace, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedNamespacesServiceServer) Update(context.Context, *namespaces.Namespace) (*namespaces.Namespace, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedNamespacesServiceServer) Delete(context.Context, *namespaces.Namespace) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedNamespacesServiceServer) Accessibles(context.Context, *namespaces.Namespace) (*access.Nodes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Accessibles not implemented")
}
func (UnimplementedNamespacesServiceServer) Deletables(context.Context, *namespaces.Namespace) (*access.Nodes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deletables not implemented")
}
func (UnimplementedNamespacesServiceServer) Joins(context.Context, *namespaces.Namespace) (*accounts.Accounts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Joins not implemented")
}
func (UnimplementedNamespacesServiceServer) Join(context.Context, *JoinRequest) (*accounts.Accounts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedNamespacesServiceServer) mustEmbedUnimplementedNamespacesServiceServer() {}

// UnsafeNamespacesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NamespacesServiceServer will
// result in compilation errors.
type UnsafeNamespacesServiceServer interface {
	mustEmbedUnimplementedNamespacesServiceServer()
}

func RegisterNamespacesServiceServer(s grpc.ServiceRegistrar, srv NamespacesServiceServer) {
	s.RegisterService(&NamespacesService_ServiceDesc, srv)
}

func _NamespacesService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(namespaces.Namespace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespacesService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServiceServer).Get(ctx, req.(*namespaces.Namespace))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamespacesService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespacesService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServiceServer).List(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamespacesService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(namespaces.Namespace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespacesService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServiceServer).Create(ctx, req.(*namespaces.Namespace))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamespacesService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(namespaces.Namespace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespacesService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServiceServer).Update(ctx, req.(*namespaces.Namespace))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamespacesService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(namespaces.Namespace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespacesService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServiceServer).Delete(ctx, req.(*namespaces.Namespace))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamespacesService_Accessibles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(namespaces.Namespace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServiceServer).Accessibles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespacesService_Accessibles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServiceServer).Accessibles(ctx, req.(*namespaces.Namespace))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamespacesService_Deletables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(namespaces.Namespace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServiceServer).Deletables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespacesService_Deletables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServiceServer).Deletables(ctx, req.(*namespaces.Namespace))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamespacesService_Joins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(namespaces.Namespace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServiceServer).Joins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespacesService_Joins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServiceServer).Joins(ctx, req.(*namespaces.Namespace))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamespacesService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespacesService_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServiceServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NamespacesService_ServiceDesc is the grpc.ServiceDesc for NamespacesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NamespacesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.node.NamespacesService",
	HandlerType: (*NamespacesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _NamespacesService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _NamespacesService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _NamespacesService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _NamespacesService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _NamespacesService_Delete_Handler,
		},
		{
			MethodName: "Accessibles",
			Handler:    _NamespacesService_Accessibles_Handler,
		},
		{
			MethodName: "Deletables",
			Handler:    _NamespacesService_Deletables_Handler,
		},
		{
			MethodName: "Joins",
			Handler:    _NamespacesService_Joins_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _NamespacesService_Join_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node/node.proto",
}

const (
	DevicesService_Get_FullMethodName              = "/infinimesh.node.DevicesService/Get"
	DevicesService_List_FullMethodName             = "/infinimesh.node.DevicesService/List"
	DevicesService_Create_FullMethodName           = "/infinimesh.node.DevicesService/Create"
	DevicesService_Update_FullMethodName           = "/infinimesh.node.DevicesService/Update"
	DevicesService_PatchConfig_FullMethodName      = "/infinimesh.node.DevicesService/PatchConfig"
	DevicesService_Delete_FullMethodName           = "/infinimesh.node.DevicesService/Delete"
	DevicesService_Toggle_FullMethodName           = "/infinimesh.node.DevicesService/Toggle"
	DevicesService_ToggleBasic_FullMethodName      = "/infinimesh.node.DevicesService/ToggleBasic"
	DevicesService_MakeDevicesToken_FullMethodName = "/infinimesh.node.DevicesService/MakeDevicesToken"
	DevicesService_Move_FullMethodName             = "/infinimesh.node.DevicesService/Move"
	DevicesService_Joins_FullMethodName            = "/infinimesh.node.DevicesService/Joins"
	DevicesService_Join_FullMethodName             = "/infinimesh.node.DevicesService/Join"
	DevicesService_GetByToken_FullMethodName       = "/infinimesh.node.DevicesService/GetByToken"
	DevicesService_GetByFingerprint_FullMethodName = "/infinimesh.node.DevicesService/GetByFingerprint"
)

// DevicesServiceClient is the client API for DevicesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DevicesServiceClient interface {
	Get(ctx context.Context, in *devices.Device, opts ...grpc.CallOption) (*devices.Device, error)
	List(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*devices.Devices, error)
	Create(ctx context.Context, in *devices.CreateRequest, opts ...grpc.CallOption) (*devices.CreateResponse, error)
	Update(ctx context.Context, in *devices.Device, opts ...grpc.CallOption) (*devices.Device, error)
	PatchConfig(ctx context.Context, in *devices.Device, opts ...grpc.CallOption) (*devices.Device, error)
	Delete(ctx context.Context, in *devices.Device, opts ...grpc.CallOption) (*DeleteResponse, error)
	Toggle(ctx context.Context, in *devices.Device, opts ...grpc.CallOption) (*devices.Device, error)
	ToggleBasic(ctx context.Context, in *devices.Device, opts ...grpc.CallOption) (*devices.Device, error)
	MakeDevicesToken(ctx context.Context, in *DevicesTokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	// Moves Device between Namespaces
	Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	// Accounts and Namesapces having access to this Device
	Joins(ctx context.Context, in *devices.Device, opts ...grpc.CallOption) (*access.Nodes, error)
	// Sets Access to this namespace for the given Node(Account or Namespace)
	// (deletes if level is set to NONE(0)) Node is interpret as a Device (uuid is
	// enough) and Join as an Account or Namespace (must be provided fully)
	Join(ctx context.Context, in *JoinGeneralRequest, opts ...grpc.CallOption) (*access.Node, error)
	GetByToken(ctx context.Context, in *devices.Device, opts ...grpc.CallOption) (*devices.Device, error)
	GetByFingerprint(ctx context.Context, in *devices.GetByFingerprintRequest, opts ...grpc.CallOption) (*devices.Device, error)
}

type devicesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDevicesServiceClient(cc grpc.ClientConnInterface) DevicesServiceClient {
	return &devicesServiceClient{cc}
}

func (c *devicesServiceClient) Get(ctx context.Context, in *devices.Device, opts ...grpc.CallOption) (*devices.Device, error) {
	out := new(devices.Device)
	err := c.cc.Invoke(ctx, DevicesService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) List(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*devices.Devices, error) {
	out := new(devices.Devices)
	err := c.cc.Invoke(ctx, DevicesService_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) Create(ctx context.Context, in *devices.CreateRequest, opts ...grpc.CallOption) (*devices.CreateResponse, error) {
	out := new(devices.CreateResponse)
	err := c.cc.Invoke(ctx, DevicesService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) Update(ctx context.Context, in *devices.Device, opts ...grpc.CallOption) (*devices.Device, error) {
	out := new(devices.Device)
	err := c.cc.Invoke(ctx, DevicesService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) PatchConfig(ctx context.Context, in *devices.Device, opts ...grpc.CallOption) (*devices.Device, error) {
	out := new(devices.Device)
	err := c.cc.Invoke(ctx, DevicesService_PatchConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) Delete(ctx context.Context, in *devices.Device, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, DevicesService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) Toggle(ctx context.Context, in *devices.Device, opts ...grpc.CallOption) (*devices.Device, error) {
	out := new(devices.Device)
	err := c.cc.Invoke(ctx, DevicesService_Toggle_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) ToggleBasic(ctx context.Context, in *devices.Device, opts ...grpc.CallOption) (*devices.Device, error) {
	out := new(devices.Device)
	err := c.cc.Invoke(ctx, DevicesService_ToggleBasic_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) MakeDevicesToken(ctx context.Context, in *DevicesTokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, DevicesService_MakeDevicesToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, DevicesService_Move_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) Joins(ctx context.Context, in *devices.Device, opts ...grpc.CallOption) (*access.Nodes, error) {
	out := new(access.Nodes)
	err := c.cc.Invoke(ctx, DevicesService_Joins_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) Join(ctx context.Context, in *JoinGeneralRequest, opts ...grpc.CallOption) (*access.Node, error) {
	out := new(access.Node)
	err := c.cc.Invoke(ctx, DevicesService_Join_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) GetByToken(ctx context.Context, in *devices.Device, opts ...grpc.CallOption) (*devices.Device, error) {
	out := new(devices.Device)
	err := c.cc.Invoke(ctx, DevicesService_GetByToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) GetByFingerprint(ctx context.Context, in *devices.GetByFingerprintRequest, opts ...grpc.CallOption) (*devices.Device, error) {
	out := new(devices.Device)
	err := c.cc.Invoke(ctx, DevicesService_GetByFingerprint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevicesServiceServer is the server API for DevicesService service.
// All implementations must embed UnimplementedDevicesServiceServer
// for forward compatibility
type DevicesServiceServer interface {
	Get(context.Context, *devices.Device) (*devices.Device, error)
	List(context.Context, *QueryRequest) (*devices.Devices, error)
	Create(context.Context, *devices.CreateRequest) (*devices.CreateResponse, error)
	Update(context.Context, *devices.Device) (*devices.Device, error)
	PatchConfig(context.Context, *devices.Device) (*devices.Device, error)
	Delete(context.Context, *devices.Device) (*DeleteResponse, error)
	Toggle(context.Context, *devices.Device) (*devices.Device, error)
	ToggleBasic(context.Context, *devices.Device) (*devices.Device, error)
	MakeDevicesToken(context.Context, *DevicesTokenRequest) (*TokenResponse, error)
	// Moves Device between Namespaces
	Move(context.Context, *MoveRequest) (*EmptyMessage, error)
	// Accounts and Namesapces having access to this Device
	Joins(context.Context, *devices.Device) (*access.Nodes, error)
	// Sets Access to this namespace for the given Node(Account or Namespace)
	// (deletes if level is set to NONE(0)) Node is interpret as a Device (uuid is
	// enough) and Join as an Account or Namespace (must be provided fully)
	Join(context.Context, *JoinGeneralRequest) (*access.Node, error)
	GetByToken(context.Context, *devices.Device) (*devices.Device, error)
	GetByFingerprint(context.Context, *devices.GetByFingerprintRequest) (*devices.Device, error)
	mustEmbedUnimplementedDevicesServiceServer()
}

// UnimplementedDevicesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDevicesServiceServer struct {
}

func (UnimplementedDevicesServiceServer) Get(context.Context, *devices.Device) (*devices.Device, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDevicesServiceServer) List(context.Context, *QueryRequest) (*devices.Devices, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDevicesServiceServer) Create(context.Context, *devices.CreateRequest) (*devices.CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDevicesServiceServer) Update(context.Context, *devices.Device) (*devices.Device, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedDevicesServiceServer) PatchConfig(context.Context, *devices.Device) (*devices.Device, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchConfig not implemented")
}
func (UnimplementedDevicesServiceServer) Delete(context.Context, *devices.Device) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDevicesServiceServer) Toggle(context.Context, *devices.Device) (*devices.Device, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Toggle not implemented")
}
func (UnimplementedDevicesServiceServer) ToggleBasic(context.Context, *devices.Device) (*devices.Device, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleBasic not implemented")
}
func (UnimplementedDevicesServiceServer) MakeDevicesToken(context.Context, *DevicesTokenRequest) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeDevicesToken not implemented")
}
func (UnimplementedDevicesServiceServer) Move(context.Context, *MoveRequest) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Move not implemented")
}
func (UnimplementedDevicesServiceServer) Joins(context.Context, *devices.Device) (*access.Nodes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Joins not implemented")
}
func (UnimplementedDevicesServiceServer) Join(context.Context, *JoinGeneralRequest) (*access.Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedDevicesServiceServer) GetByToken(context.Context, *devices.Device) (*devices.Device, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByToken not implemented")
}
func (UnimplementedDevicesServiceServer) GetByFingerprint(context.Context, *devices.GetByFingerprintRequest) (*devices.Device, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByFingerprint not implemented")
}
func (UnimplementedDevicesServiceServer) mustEmbedUnimplementedDevicesServiceServer() {}

// UnsafeDevicesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DevicesServiceServer will
// result in compilation errors.
type UnsafeDevicesServiceServer interface {
	mustEmbedUnimplementedDevicesServiceServer()
}

func RegisterDevicesServiceServer(s grpc.ServiceRegistrar, srv DevicesServiceServer) {
	s.RegisterService(&DevicesService_ServiceDesc, srv)
}

func _DevicesService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(devices.Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevicesService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).Get(ctx, req.(*devices.Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevicesService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).List(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(devices.CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevicesService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).Create(ctx, req.(*devices.CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(devices.Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevicesService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).Update(ctx, req.(*devices.Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_PatchConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(devices.Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).PatchConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevicesService_PatchConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).PatchConfig(ctx, req.(*devices.Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(devices.Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevicesService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).Delete(ctx, req.(*devices.Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_Toggle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(devices.Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).Toggle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevicesService_Toggle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).Toggle(ctx, req.(*devices.Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_ToggleBasic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(devices.Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).ToggleBasic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevicesService_ToggleBasic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).ToggleBasic(ctx, req.(*devices.Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_MakeDevicesToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevicesTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).MakeDevicesToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevicesService_MakeDevicesToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).MakeDevicesToken(ctx, req.(*DevicesTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevicesService_Move_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).Move(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_Joins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(devices.Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).Joins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevicesService_Joins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).Joins(ctx, req.(*devices.Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGeneralRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevicesService_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).Join(ctx, req.(*JoinGeneralRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_GetByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(devices.Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).GetByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevicesService_GetByToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).GetByToken(ctx, req.(*devices.Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_GetByFingerprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(devices.GetByFingerprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).GetByFingerprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevicesService_GetByFingerprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).GetByFingerprint(ctx, req.(*devices.GetByFingerprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DevicesService_ServiceDesc is the grpc.ServiceDesc for DevicesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DevicesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.node.DevicesService",
	HandlerType: (*DevicesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _DevicesService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _DevicesService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _DevicesService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DevicesService_Update_Handler,
		},
		{
			MethodName: "PatchConfig",
			Handler:    _DevicesService_PatchConfig_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DevicesService_Delete_Handler,
		},
		{
			MethodName: "Toggle",
			Handler:    _DevicesService_Toggle_Handler,
		},
		{
			MethodName: "ToggleBasic",
			Handler:    _DevicesService_ToggleBasic_Handler,
		},
		{
			MethodName: "MakeDevicesToken",
			Handler:    _DevicesService_MakeDevicesToken_Handler,
		},
		{
			MethodName: "Move",
			Handler:    _DevicesService_Move_Handler,
		},
		{
			MethodName: "Joins",
			Handler:    _DevicesService_Joins_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _DevicesService_Join_Handler,
		},
		{
			MethodName: "GetByToken",
			Handler:    _DevicesService_GetByToken_Handler,
		},
		{
			MethodName: "GetByFingerprint",
			Handler:    _DevicesService_GetByFingerprint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node/node.proto",
}

const (
	ShadowService_Get_FullMethodName              = "/infinimesh.node.ShadowService/Get"
	ShadowService_Patch_FullMethodName            = "/infinimesh.node.ShadowService/Patch"
	ShadowService_Remove_FullMethodName           = "/infinimesh.node.ShadowService/Remove"
	ShadowService_StreamShadow_FullMethodName     = "/infinimesh.node.ShadowService/StreamShadow"
	ShadowService_StreamShadowSync_FullMethodName = "/infinimesh.node.ShadowService/StreamShadowSync"
)

// ShadowServiceClient is the client API for ShadowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShadowServiceClient interface {
	Get(ctx context.Context, in *shadow.GetRequest, opts ...grpc.CallOption) (*shadow.GetResponse, error)
	Patch(ctx context.Context, in *shadow.Shadow, opts ...grpc.CallOption) (*shadow.Shadow, error)
	Remove(ctx context.Context, in *shadow.RemoveRequest, opts ...grpc.CallOption) (*shadow.Shadow, error)
	StreamShadow(ctx context.Context, in *shadow.StreamShadowRequest, opts ...grpc.CallOption) (ShadowService_StreamShadowClient, error)
	StreamShadowSync(ctx context.Context, in *shadow.StreamShadowRequest, opts ...grpc.CallOption) (ShadowService_StreamShadowSyncClient, error)
}

type shadowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShadowServiceClient(cc grpc.ClientConnInterface) ShadowServiceClient {
	return &shadowServiceClient{cc}
}

func (c *shadowServiceClient) Get(ctx context.Context, in *shadow.GetRequest, opts ...grpc.CallOption) (*shadow.GetResponse, error) {
	out := new(shadow.GetResponse)
	err := c.cc.Invoke(ctx, ShadowService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shadowServiceClient) Patch(ctx context.Context, in *shadow.Shadow, opts ...grpc.CallOption) (*shadow.Shadow, error) {
	out := new(shadow.Shadow)
	err := c.cc.Invoke(ctx, ShadowService_Patch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shadowServiceClient) Remove(ctx context.Context, in *shadow.RemoveRequest, opts ...grpc.CallOption) (*shadow.Shadow, error) {
	out := new(shadow.Shadow)
	err := c.cc.Invoke(ctx, ShadowService_Remove_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shadowServiceClient) StreamShadow(ctx context.Context, in *shadow.StreamShadowRequest, opts ...grpc.CallOption) (ShadowService_StreamShadowClient, error) {
	stream, err := c.cc.NewStream(ctx, &ShadowService_ServiceDesc.Streams[0], ShadowService_StreamShadow_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &shadowServiceStreamShadowClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ShadowService_StreamShadowClient interface {
	Recv() (*shadow.Shadow, error)
	grpc.ClientStream
}

type shadowServiceStreamShadowClient struct {
	grpc.ClientStream
}

func (x *shadowServiceStreamShadowClient) Recv() (*shadow.Shadow, error) {
	m := new(shadow.Shadow)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *shadowServiceClient) StreamShadowSync(ctx context.Context, in *shadow.StreamShadowRequest, opts ...grpc.CallOption) (ShadowService_StreamShadowSyncClient, error) {
	stream, err := c.cc.NewStream(ctx, &ShadowService_ServiceDesc.Streams[1], ShadowService_StreamShadowSync_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &shadowServiceStreamShadowSyncClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ShadowService_StreamShadowSyncClient interface {
	Recv() (*shadow.Shadow, error)
	grpc.ClientStream
}

type shadowServiceStreamShadowSyncClient struct {
	grpc.ClientStream
}

func (x *shadowServiceStreamShadowSyncClient) Recv() (*shadow.Shadow, error) {
	m := new(shadow.Shadow)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ShadowServiceServer is the server API for ShadowService service.
// All implementations must embed UnimplementedShadowServiceServer
// for forward compatibility
type ShadowServiceServer interface {
	Get(context.Context, *shadow.GetRequest) (*shadow.GetResponse, error)
	Patch(context.Context, *shadow.Shadow) (*shadow.Shadow, error)
	Remove(context.Context, *shadow.RemoveRequest) (*shadow.Shadow, error)
	StreamShadow(*shadow.StreamShadowRequest, ShadowService_StreamShadowServer) error
	StreamShadowSync(*shadow.StreamShadowRequest, ShadowService_StreamShadowSyncServer) error
	mustEmbedUnimplementedShadowServiceServer()
}

// UnimplementedShadowServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShadowServiceServer struct {
}

func (UnimplementedShadowServiceServer) Get(context.Context, *shadow.GetRequest) (*shadow.GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedShadowServiceServer) Patch(context.Context, *shadow.Shadow) (*shadow.Shadow, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedShadowServiceServer) Remove(context.Context, *shadow.RemoveRequest) (*shadow.Shadow, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedShadowServiceServer) StreamShadow(*shadow.StreamShadowRequest, ShadowService_StreamShadowServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamShadow not implemented")
}
func (UnimplementedShadowServiceServer) StreamShadowSync(*shadow.StreamShadowRequest, ShadowService_StreamShadowSyncServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamShadowSync not implemented")
}
func (UnimplementedShadowServiceServer) mustEmbedUnimplementedShadowServiceServer() {}

// UnsafeShadowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShadowServiceServer will
// result in compilation errors.
type UnsafeShadowServiceServer interface {
	mustEmbedUnimplementedShadowServiceServer()
}

func RegisterShadowServiceServer(s grpc.ServiceRegistrar, srv ShadowServiceServer) {
	s.RegisterService(&ShadowService_ServiceDesc, srv)
}

func _ShadowService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(shadow.GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShadowServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShadowService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShadowServiceServer).Get(ctx, req.(*shadow.GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShadowService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(shadow.Shadow)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShadowServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShadowService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShadowServiceServer).Patch(ctx, req.(*shadow.Shadow))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShadowService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(shadow.RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShadowServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShadowService_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShadowServiceServer).Remove(ctx, req.(*shadow.RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShadowService_StreamShadow_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(shadow.StreamShadowRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShadowServiceServer).StreamShadow(m, &shadowServiceStreamShadowServer{stream})
}

type ShadowService_StreamShadowServer interface {
	Send(*shadow.Shadow) error
	grpc.ServerStream
}

type shadowServiceStreamShadowServer struct {
	grpc.ServerStream
}

func (x *shadowServiceStreamShadowServer) Send(m *shadow.Shadow) error {
	return x.ServerStream.SendMsg(m)
}

func _ShadowService_StreamShadowSync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(shadow.StreamShadowRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShadowServiceServer).StreamShadowSync(m, &shadowServiceStreamShadowSyncServer{stream})
}

type ShadowService_StreamShadowSyncServer interface {
	Send(*shadow.Shadow) error
	grpc.ServerStream
}

type shadowServiceStreamShadowSyncServer struct {
	grpc.ServerStream
}

func (x *shadowServiceStreamShadowSyncServer) Send(m *shadow.Shadow) error {
	return x.ServerStream.SendMsg(m)
}

// ShadowService_ServiceDesc is the grpc.ServiceDesc for ShadowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShadowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.node.ShadowService",
	HandlerType: (*ShadowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ShadowService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _ShadowService_Patch_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _ShadowService_Remove_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamShadow",
			Handler:       _ShadowService_StreamShadow_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamShadowSync",
			Handler:       _ShadowService_StreamShadowSync_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "node/node.proto",
}

const (
	InternalService_GetLDAPProviders_FullMethodName = "/infinimesh.node.InternalService/GetLDAPProviders"
)

// InternalServiceClient is the client API for InternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalServiceClient interface {
	GetLDAPProviders(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*LDAPProviders, error)
}

type internalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalServiceClient(cc grpc.ClientConnInterface) InternalServiceClient {
	return &internalServiceClient{cc}
}

func (c *internalServiceClient) GetLDAPProviders(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*LDAPProviders, error) {
	out := new(LDAPProviders)
	err := c.cc.Invoke(ctx, InternalService_GetLDAPProviders_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalServiceServer is the server API for InternalService service.
// All implementations must embed UnimplementedInternalServiceServer
// for forward compatibility
type InternalServiceServer interface {
	GetLDAPProviders(context.Context, *EmptyMessage) (*LDAPProviders, error)
	mustEmbedUnimplementedInternalServiceServer()
}

// UnimplementedInternalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInternalServiceServer struct {
}

func (UnimplementedInternalServiceServer) GetLDAPProviders(context.Context, *EmptyMessage) (*LDAPProviders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLDAPProviders not implemented")
}
func (UnimplementedInternalServiceServer) mustEmbedUnimplementedInternalServiceServer() {}

// UnsafeInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalServiceServer will
// result in compilation errors.
type UnsafeInternalServiceServer interface {
	mustEmbedUnimplementedInternalServiceServer()
}

func RegisterInternalServiceServer(s grpc.ServiceRegistrar, srv InternalServiceServer) {
	s.RegisterService(&InternalService_ServiceDesc, srv)
}

func _InternalService_GetLDAPProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GetLDAPProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_GetLDAPProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GetLDAPProviders(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalService_ServiceDesc is the grpc.ServiceDesc for InternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.node.InternalService",
	HandlerType: (*InternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLDAPProviders",
			Handler:    _InternalService_GetLDAPProviders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node/node.proto",
}
