name: Generate Protobuf Client Libraries

on:
  pull_request:

jobs:
  generate-es:
    name: Generate Protobuf Client Libraries for ES
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm install
      - name: Generate Connect-ES library
        run: npm run generate
      
      - name: Git commit and push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Continuous Integration Build Protobuf Client Libraries for ES
          add: 'build/es'